import { InventoryItem, JewelryCategory } from "@/types/inventory";

// In-memory cache for inventory data
class InventoryCache {
  private cache: Map<string, InventoryItem> = new Map();
  private initialized = false;

  // Initialize cache with sample data
  initialize(): void {
    if (this.initialized) return;

    const sampleData = this.generateSampleData();
    sampleData.forEach((item) => {
      this.cache.set(item.id, item);
    });

    this.initialized = true;
  }

  // Get all items, optionally filtered by category
  getAll(category?: JewelryCategory): InventoryItem[] {
    this.initialize();
    const items = Array.from(this.cache.values());
    
    if (category && category !== "All") {
      return items.filter((item) => item.category === category);
    }
    
    return items;
  }

  // Get item by ID
  getById(id: string): InventoryItem | null {
    this.initialize();
    return this.cache.get(id) || null;
  }

  // Add or update item
  set(item: InventoryItem): void {
    this.cache.set(item.id, item);
  }

  // Delete item
  delete(id: string): boolean {
    return this.cache.delete(id);
  }

  // Clear cache
  clear(): void {
    this.cache.clear();
    this.initialized = false;
  }

  // Generate comprehensive sample data
  private generateSampleData(): InventoryItem[] {
    const now = new Date().toISOString();
    
    // Helper to generate local image paths
    const img = (category: string, name: string) => {
      const categoryLower = category.toLowerCase();
      const nameSlug = name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
      return `/images/${categoryLower}/${nameSlug}.jpg`;
    };
    
    return [
      // RINGS
      {
        id: "ring-001",
        name: "Classic 18K Gold Wedding Ring",
        description: "Elegant and timeless 18K gold wedding ring with a smooth finish. Perfect for everyday wear and special occasions. Crafted with precision and attention to detail.",
        category: "Rings",
        price: 1850,
        weight: 6.5,
        material: "Gold",
        karat: 18,
        images: [img("Rings", "Classic 18K Gold Wedding Ring")],
        inStock: true,
        sku: "RING-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ring-002",
        name: "Diamond Solitaire Engagement Ring",
        description: "Stunning 1.5 carat diamond solitaire set in 22K gold. The center stone is certified and features excellent cut, color, and clarity. A symbol of eternal love.",
        category: "Rings",
        price: 8500,
        weight: 8.2,
        material: "Gold",
        karat: 22,
        images: [img("Rings", "Diamond Solitaire Engagement Ring")],
        inStock: true,
        sku: "RING-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ring-003",
        name: "Vintage Art Deco Ring",
        description: "Beautiful vintage-inspired art deco ring featuring intricate geometric patterns. Set with small diamonds and crafted in 18K gold.",
        category: "Rings",
        price: 3200,
        weight: 7.8,
        material: "Gold",
        karat: 18,
        images: [img("Rings", "Vintage Art Deco Ring")],
        inStock: true,
        sku: "RING-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ring-004",
        name: "Platinum Eternity Band",
        description: "Luxurious platinum eternity band with channel-set diamonds. Perfect for stacking or as a standalone piece. Hypoallergenic and durable.",
        category: "Rings",
        price: 4200,
        weight: 5.5,
        material: "Platinum",
        images: [img("Rings", "Platinum Eternity Band")],
        inStock: true,
        sku: "RING-004",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ring-005",
        name: "Rose Gold Stackable Ring Set",
        description: "Set of three delicate rose gold stackable rings. Mix and match for a personalized look. Each ring features a unique design element.",
        category: "Rings",
        price: 950,
        weight: 4.2,
        material: "Gold",
        karat: 14,
        images: [img("Rings", "Rose Gold Stackable Ring Set")],
        inStock: true,
        sku: "RING-005",
        createdAt: now,
        updatedAt: now,
      },

      // NECKLACES
      {
        id: "necklace-001",
        name: "Pearl Strand Necklace",
        description: "Classic 18-inch cultured pearl strand necklace with 14K gold clasp. Timeless elegance that complements any outfit. Perfect for formal occasions.",
        category: "Necklaces",
        price: 2800,
        weight: 25.5,
        material: "Gold",
        karat: 14,
        images: [img("Necklaces", "Pearl Strand Necklace")],
        inStock: true,
        sku: "NECK-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "necklace-002",
        name: "Diamond Pendant Necklace",
        description: "Exquisite 22K gold chain with a stunning 2-carat diamond pendant. The pendant features a modern design with excellent craftsmanship.",
        category: "Necklaces",
        price: 12500,
        weight: 18.2,
        material: "Gold",
        karat: 22,
        images: [img("Necklaces", "Diamond Pendant Necklace")],
        videos: ["/videos/necklaces/diamond-pendant-showcase.mp4"],
        inStock: true,
        sku: "NECK-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "necklace-003",
        name: "Gold Choker with Gemstones",
        description: "Beautiful 18K gold choker necklace adorned with emeralds and diamonds. The perfect statement piece for special events.",
        category: "Necklaces",
        price: 6800,
        weight: 22.8,
        material: "Gold",
        karat: 18,
        images: [img("Necklaces", "Gold Choker with Gemstones")],
        inStock: true,
        sku: "NECK-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "necklace-004",
        name: "Layered Gold Chain Set",
        description: "Set of three 18K gold chains in varying lengths. Can be worn together for a trendy layered look or individually.",
        category: "Necklaces",
        price: 2400,
        weight: 15.5,
        material: "Gold",
        karat: 18,
        images: [img("Necklaces", "Layered Gold Chain Set")],
        inStock: true,
        sku: "NECK-004",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "necklace-005",
        name: "Vintage Locket Necklace",
        description: "Antique-style 14K gold locket necklace. Opens to reveal space for photos. A sentimental piece perfect for keeping memories close.",
        category: "Necklaces",
        price: 1650,
        weight: 12.3,
        material: "Gold",
        karat: 14,
        images: [img("Necklaces", "Vintage Locket Necklace")],
        inStock: false,
        sku: "NECK-005",
        createdAt: now,
        updatedAt: now,
      },

      // EARRINGS
      {
        id: "earring-001",
        name: "Diamond Stud Earrings",
        description: "Classic 1-carat diamond stud earrings in 18K gold settings. Secure screw-back posts. A must-have in every jewelry collection.",
        category: "Earrings",
        price: 3500,
        weight: 4.8,
        material: "Gold",
        karat: 18,
        images: [img("Earrings", "Diamond Stud Earrings")],
        inStock: true,
        sku: "EARR-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "earring-002",
        name: "Pearl Drop Earrings",
        description: "Elegant 14K gold drop earrings featuring cultured pearls. Perfect length for both casual and formal wear.",
        category: "Earrings",
        price: 1200,
        weight: 5.2,
        material: "Gold",
        karat: 14,
        images: [img("Earrings", "Pearl Drop Earrings")],
        inStock: true,
        sku: "EARR-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "earring-003",
        name: "Hoop Earrings 22K Gold",
        description: "Large 22K gold hoop earrings with a modern twist. Lightweight yet substantial. Perfect for making a statement.",
        category: "Earrings",
        price: 2200,
        weight: 8.5,
        material: "Gold",
        karat: 22,
        images: [img("Earrings", "Hoop Earrings 22K Gold")],
        inStock: true,
        sku: "EARR-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "earring-004",
        name: "Chandelier Earrings with Crystals",
        description: "Dramatic chandelier-style earrings in 18K gold with crystal accents. Perfect for evening events and special occasions.",
        category: "Earrings",
        price: 2800,
        weight: 12.3,
        material: "Gold",
        karat: 18,
        images: ["/images/earrings/chandelier-earrings-with-crystals.jpg"],
        videos: ["/videos/earrings/chandelier-showcase.mp4"],
        inStock: true,
        sku: "EARR-004",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "earring-005",
        name: "Minimalist Gold Huggies",
        description: "Small, comfortable 14K gold huggie earrings. Perfect for everyday wear and sleeping. Sleek and modern design.",
        category: "Earrings",
        price: 450,
        weight: 2.1,
        material: "Gold",
        karat: 14,
        images: [img("Earrings", "Minimalist Gold Huggies")],
        inStock: true,
        sku: "EARR-005",
        createdAt: now,
        updatedAt: now,
      },

      // BRACELETS
      {
        id: "bracelet-001",
        name: "Tennis Bracelet Diamond",
        description: "Stunning 18K gold tennis bracelet with channel-set diamonds. Flexible and comfortable fit. A classic piece that never goes out of style.",
        category: "Bracelets",
        price: 8500,
        weight: 18.5,
        material: "Gold",
        karat: 18,
        images: [img("Bracelets", "Tennis Bracelet Diamond")],
        inStock: true,
        sku: "BRAC-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bracelet-002",
        name: "Gold Bangle Set",
        description: "Set of three 22K gold bangles with traditional designs. Can be worn together or separately. Perfect for stacking.",
        category: "Bracelets",
        price: 3200,
        weight: 45.2,
        material: "Gold",
        karat: 22,
        images: [img("Bracelets", "Gold Bangle Set")],
        inStock: true,
        sku: "BRAC-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bracelet-003",
        name: "Charm Bracelet 18K Gold",
        description: "Personalizable 18K gold charm bracelet with initial charms. Add more charms to tell your unique story.",
        category: "Bracelets",
        price: 1800,
        weight: 12.8,
        material: "Gold",
        karat: 18,
        images: [img("Bracelets", "Charm Bracelet 18K Gold")],
        inStock: true,
        sku: "BRAC-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bracelet-004",
        name: "Cuff Bracelet with Gemstones",
        description: "Bold 18K gold cuff bracelet featuring sapphires and diamonds. Adjustable fit. Makes a strong fashion statement.",
        category: "Bracelets",
        price: 5200,
        weight: 28.5,
        material: "Gold",
        karat: 18,
        images: [img("Bracelets", "Cuff Bracelet with Gemstones")],
        inStock: true,
        sku: "BRAC-004",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bracelet-005",
        name: "Link Chain Bracelet",
        description: "Classic 14K gold link chain bracelet with secure clasp. Versatile design that pairs with any style.",
        category: "Bracelets",
        price: 950,
        weight: 8.2,
        material: "Gold",
        karat: 14,
        images: [img("Bracelets", "Link Chain Bracelet")],
        inStock: true,
        sku: "BRAC-005",
        createdAt: now,
        updatedAt: now,
      },

      // PENDANTS
      {
        id: "pendant-001",
        name: "Heart Pendant 18K Gold",
        description: "Romantic 18K gold heart pendant on a matching chain. Perfect gift for loved ones. Available in multiple sizes.",
        category: "Pendants",
        price: 1250,
        weight: 6.5,
        material: "Gold",
        karat: 18,
        images: [img("Pendants", "Heart Pendant 18K Gold")],
        inStock: true,
        sku: "PEND-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "pendant-002",
        name: "Cross Pendant Diamond",
        description: "Elegant 22K gold cross pendant with diamond accents. A meaningful piece of faith jewelry with exceptional craftsmanship.",
        category: "Pendants",
        price: 2800,
        weight: 8.2,
        material: "Gold",
        karat: 22,
        images: [img("Pendants", "Cross Pendant Diamond")],
        inStock: true,
        sku: "PEND-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "pendant-003",
        name: "Initial Pendant Custom",
        description: "Personalized 14K gold initial pendant. Choose your letter. Comes with a 16-inch chain. Perfect for everyday wear.",
        category: "Pendants",
        price: 650,
        weight: 3.8,
        material: "Gold",
        karat: 14,
        images: [img("Pendants", "Initial Pendant Custom")],
        inStock: true,
        sku: "PEND-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "pendant-004",
        name: "Tree of Life Pendant",
        description: "Symbolic 18K gold Tree of Life pendant. Represents growth, strength, and connection. A meaningful piece with intricate detail.",
        category: "Pendants",
        price: 1450,
        weight: 7.5,
        material: "Gold",
        karat: 18,
        images: [img("Pendants", "Tree of Life Pendant")],
        inStock: true,
        sku: "PEND-004",
        createdAt: now,
        updatedAt: now,
      },

      // CHAINS
      {
        id: "chain-001",
        name: "Cuban Link Chain 22K",
        description: "Bold 22K gold Cuban link chain. Available in multiple lengths. A statement piece that never goes out of style.",
        category: "Chains",
        price: 4500,
        weight: 35.8,
        material: "Gold",
        karat: 22,
        images: [img("Chains", "Cuban Link Chain 22K")],
        inStock: true,
        sku: "CHAIN-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "chain-002",
        name: "Rope Chain 18K Gold",
        description: "Classic 18K gold rope chain. Durable and elegant. Perfect for wearing alone or with pendants.",
        category: "Chains",
        price: 2200,
        weight: 18.5,
        material: "Gold",
        karat: 18,
        images: [img("Chains", "Rope Chain 18K Gold")],
        inStock: true,
        sku: "CHAIN-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "chain-003",
        name: "Box Chain 14K Gold",
        description: "Sleek 14K gold box chain. Modern design with secure clasp. Versatile for everyday wear.",
        category: "Chains",
        price: 1200,
        weight: 12.3,
        material: "Gold",
        karat: 14,
        images: [img("Chains", "Box Chain 14K Gold")],
        inStock: true,
        sku: "CHAIN-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "chain-004",
        name: "Figaro Chain 22K Gold",
        description: "Traditional 22K gold Figaro chain. Features alternating link pattern. A timeless classic.",
        category: "Chains",
        price: 3800,
        weight: 28.2,
        material: "Gold",
        karat: 22,
        images: [img("Chains", "Figaro Chain 22K Gold")],
        inStock: true,
        sku: "CHAIN-004",
        createdAt: now,
        updatedAt: now,
      },

      // BANGLES
      {
        id: "bangle-001",
        name: "Traditional Gold Bangle",
        description: "Classic 22K gold bangle with traditional Indian design. Solid construction. A timeless piece of jewelry.",
        category: "Bangles",
        price: 2800,
        weight: 32.5,
        material: "Gold",
        karat: 22,
        images: [img("Bangles", "Traditional Gold Bangle")],
        inStock: true,
        sku: "BANG-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bangle-002",
        name: "Diamond Bangle Set",
        description: "Set of two 18K gold bangles with diamond accents. Perfect for stacking. Elegant and sophisticated.",
        category: "Bangles",
        price: 5200,
        weight: 28.8,
        material: "Gold",
        karat: 18,
        images: [img("Bangles", "Diamond Bangle Set")],
        inStock: true,
        sku: "BANG-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bangle-003",
        name: "Hinged Bangle 18K",
        description: "Convenient hinged 18K gold bangle. Easy to put on and take off. Features intricate engraved pattern.",
        category: "Bangles",
        price: 1950,
        weight: 22.3,
        material: "Gold",
        karat: 18,
        images: [img("Bangles", "Hinged Bangle 18K")],
        inStock: true,
        sku: "BANG-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bangle-004",
        name: "Open Cuff Bangle",
        description: "Modern open cuff bangle in 14K gold. Adjustable fit. Contemporary design with clean lines.",
        category: "Bangles",
        price: 1250,
        weight: 15.5,
        material: "Gold",
        karat: 14,
        images: [img("Bangles", "Open Cuff Bangle")],
        inStock: true,
        sku: "BANG-004",
        createdAt: now,
        updatedAt: now,
      },

      // ANKLETS
      {
        id: "anklet-001",
        name: "Delicate Gold Anklet",
        description: "Dainty 14K gold anklet with small charms. Adjustable length. Perfect for beach and summer wear.",
        category: "Anklets",
        price: 450,
        weight: 3.2,
        material: "Gold",
        karat: 14,
        images: [img("Anklets", "Delicate Gold Anklet")],
        inStock: true,
        sku: "ANKL-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "anklet-002",
        name: "Chain Anklet with Pendant",
        description: "Elegant 18K gold chain anklet with a small heart pendant. Adjustable clasp. A subtle statement piece.",
        category: "Anklets",
        price: 680,
        weight: 4.5,
        material: "Gold",
        karat: 18,
        images: [img("Anklets", "Chain Anklet with Pendant")],
        inStock: true,
        sku: "ANKL-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "anklet-003",
        name: "Beaded Anklet",
        description: "Stylish 14K gold beaded anklet. Comfortable and lightweight. Perfect for casual and bohemian styles.",
        category: "Anklets",
        price: 380,
        weight: 2.8,
        material: "Gold",
        karat: 14,
        images: [img("Anklets", "Beaded Anklet")],
        inStock: true,
        sku: "ANKL-003",
        createdAt: now,
        updatedAt: now,
      },

      // BROOCHES
      {
        id: "brooch-001",
        name: "Vintage Floral Brooch",
        description: "Antique-style 18K gold brooch with floral design and small diamonds. Perfect for adding elegance to jackets and blazers.",
        category: "Brooches",
        price: 2200,
        weight: 8.5,
        material: "Gold",
        karat: 18,
        images: [img("Brooches", "Vintage Floral Brooch")],
        inStock: true,
        sku: "BROO-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "brooch-002",
        name: "Art Deco Brooch",
        description: "Stunning 18K gold Art Deco brooch with geometric patterns and gemstone accents. A collector's piece.",
        category: "Brooches",
        price: 3200,
        weight: 12.3,
        material: "Gold",
        karat: 18,
        images: [img("Brooches", "Art Deco Brooch")],
        inStock: true,
        sku: "BROO-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "brooch-003",
        name: "Butterfly Brooch Diamond",
        description: "Beautiful 22K gold butterfly brooch with diamond wings. Detailed craftsmanship. A unique statement piece.",
        category: "Brooches",
        price: 4800,
        weight: 15.8,
        material: "Gold",
        karat: 22,
        images: [img("Brooches", "Butterfly Brooch Diamond")],
        inStock: true,
        sku: "BROO-003",
        createdAt: now,
        updatedAt: now,
      },

      // WATCHES
      {
        id: "watch-001",
        name: "Luxury Gold Watch",
        description: "Elegant 18K gold watch with Swiss movement. Classic design with leather strap. Water-resistant and precision-engineered.",
        category: "Watches",
        price: 12500,
        weight: 85.5,
        material: "Gold",
        karat: 18,
        images: [img("Watches", "Luxury Gold Watch")],
        inStock: true,
        sku: "WATC-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "watch-002",
        name: "Diamond Watch 22K",
        description: "Opulent 22K gold watch with diamond bezel. Automatic movement. A true luxury timepiece for special occasions.",
        category: "Watches",
        price: 18500,
        weight: 92.3,
        material: "Gold",
        karat: 22,
        images: [img("Watches", "Diamond Watch 22K")],
        videos: ["/videos/watches/diamond-watch-showcase.mp4"],
        inStock: true,
        sku: "WATC-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "watch-003",
        name: "Vintage Gold Watch",
        description: "Restored vintage 14K gold watch with original movement. Classic design from the 1950s. A collector's item.",
        category: "Watches",
        price: 6800,
        weight: 65.2,
        material: "Gold",
        karat: 14,
        images: [img("Watches", "Vintage Gold Watch")],
        inStock: true,
        sku: "WATC-003",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "watch-004",
        name: "Sport Gold Watch",
        description: "Modern 18K gold sports watch with chronograph. Water-resistant to 100m. Perfect for active lifestyles.",
        category: "Watches",
        price: 9500,
        weight: 78.5,
        material: "Gold",
        karat: 18,
        images: [img("Watches", "Sport Gold Watch")],
        inStock: true,
        sku: "WATC-004",
        createdAt: now,
        updatedAt: now,
      },

      // LIVE-PRICING SHOWCASE — non-gold materials priced from their own
      // live element rate (silver/platinum/palladium) or configured baseline
      // (bronze). Prices update with the live metal rate, not the legacy
      // `price` field (which is only a USD fallback).
      {
        id: "silver-001",
        name: "Sterling Silver Rope Necklace",
        description: "Hand-finished sterling silver (92.5%) rope necklace with a polished sheen. Priced live from the daily silver rate.",
        category: "Necklaces",
        price: 80,
        weight: 18.5,
        material: "Silver",
        images: ["/images/necklaces/pearl-strand-necklace.jpg"],
        inStock: true,
        sku: "SILV-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "silver-002",
        name: "Sterling Silver Charm Bracelet",
        description: "Delicate sterling silver (92.5%) charm bracelet, perfect for everyday wear. Priced live from the daily silver rate.",
        category: "Bracelets",
        price: 60,
        weight: 12.0,
        material: "Silver",
        images: ["/images/bracelets/link-chain-bracelet.jpg"],
        inStock: true,
        sku: "SILV-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "platinum-002",
        name: "Platinum Link Chain",
        description: "Substantial PT950 platinum link chain with a brushed finish. Priced live from the daily platinum rate.",
        category: "Chains",
        price: 1500,
        weight: 24.0,
        material: "Platinum",
        images: ["/images/chains/box-chain-14k-gold.jpg"],
        inStock: true,
        sku: "PLAT-002",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "palladium-001",
        name: "Palladium Wedding Band",
        description: "Naturally white PD950 palladium wedding band, hypoallergenic and durable. Priced live from the daily palladium rate.",
        category: "Rings",
        price: 900,
        weight: 6.5,
        material: "Palladium",
        images: ["/images/rings/platinum-eternity-band.jpg"],
        inStock: true,
        sku: "PALL-001",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "bronze-001",
        name: "Antique Bronze Brooch",
        description: "Vintage-style bronze brooch with intricate detailing. Priced from a maintained bronze baseline (bronze has no precious-metal spot market).",
        category: "Brooches",
        price: 40,
        weight: 15.0,
        material: "Bronze",
        images: ["/images/brooches/art-deco-brooch.jpg"],
        inStock: true,
        sku: "BRON-001",
        createdAt: now,
        updatedAt: now,
      },
    ];
  }
}

// Export singleton instance
export const inventoryCache = new InventoryCache();

